# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nVH2O6bHwww0dcebIrltSzoikIjVR7-p
"""

from PIL import Image
import matplotlib.pyplot as plt

c = Image.open(r"C:\Users\prana\Downloads\content.jpeg").resize((300,300))
s = Image.open(r"C:\Users\prana\Downloads\style.jpg").resize((300,300))

o = Image.blend(c, s, 0.5)

for i, img in enumerate([c, s, o]):
    plt.subplot(1,3,i+1)
    plt.imshow(img)
    plt.axis('off')
plt.show()

o.save("output.jpg")