# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nVH2O6bHwww0dcebIrltSzoikIjVR7-p
"""

servers = [0,0,0]
requests = [5,3,7,2,6]

print("Round Robin:")
for i,r in enumerate(requests):
    idx = i % len(servers)
    servers[idx] += r
    print(f"{r} \u2192 Server {idx}")
print("After Round Robin:", servers)

# Reset
servers = [0,0,0]

print("\nLeast Load:")
for r in requests:
    idx = servers.index(min(servers))
    servers[idx] += r
    print(f"{r} \u2192 Server {idx}")
print("Final Load:", servers)

